# Generated by Django 5.0.2 on 2024-04-11 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('endereco', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Emitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(max_length=20)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.CharField(max_length=100)),
                ('ncm_sh', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('serie', models.CharField(blank=True, max_length=20, null=True)),
                ('data_emissao', models.DateField()),
                ('data_operacao', models.DateField()),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True)),
                ('natureza_operacao', models.CharField(max_length=255)),
                ('cfop', models.CharField(max_length=4)),
                ('informacoes_adicionais', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_notas.categoria')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_recebidas', to='gestao_notas.destinatario')),
                ('emitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_emitidas', to='gestao_notas.emitente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_notas.nota')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_notas.produto')),
            ],
            options={
                'unique_together': {('nota', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='nota',
            name='produtos',
            field=models.ManyToManyField(through='gestao_notas.ItemNota', to='gestao_notas.produto'),
        ),
    ]
