# Generated by Django 5.0.4 on 2024-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_notas", "0003_rename_valor_rateionota_ratio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="nota",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="rateionota",
            name="centro_de_custo",
        ),
        migrations.RemoveField(
            model_name="nota",
            name="destinatario",
        ),
        migrations.RemoveField(
            model_name="nota",
            name="emitente",
        ),
        migrations.AlterUniqueTogether(
            name="itemnota",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="itemnota",
            name="nota",
        ),
        migrations.RemoveField(
            model_name="itemnota",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="nota",
            name="produtos",
        ),
        migrations.RemoveField(
            model_name="rateionota",
            name="nota",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="CentroDeCusto",
        ),
        migrations.DeleteModel(
            name="Destinatario",
        ),
        migrations.DeleteModel(
            name="Emitente",
        ),
        migrations.DeleteModel(
            name="ItemNota",
        ),
        migrations.DeleteModel(
            name="Produto",
        ),
        migrations.DeleteModel(
            name="Nota",
        ),
        migrations.DeleteModel(
            name="RateioNota",
        ),
    ]
